# Generated by Django 5.2.8 on 2025-11-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='direction',
            field=models.CharField(choices=[('in', 'Kirish'), ('out', 'Chiqish')], default='in', max_length=5),
            preserve_default=False,
        ),
    ]
