# Generated by Django 5.2.8 on 2026-05-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventlog_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
